ARG PYTHON_VERSION=3.10
ARG DEBIAN_VERSION=bullseye

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION}

RUN apt-get update && apt-get install -y gcc \
    && pip install --no-cache-dir python-Levenshtein==0.12.* \
    && apt-get purge -y gcc && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
